env:
    commonjs: true
    es6: true
    node: true
    mocha: true
extends:
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
rules: {
  indent: ["error", "tab"],
  no-tabs: 0,
  no-param-reassign: 0,
  func-names: 0,
  max-len: [1, 150, 4]
}